# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikto_b/Documents/C++/fantastic-train/waypointmanager

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikto_b/Documents/C++/fantastic-train/waypointmanager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikto_b/Documents/C++/fantastic-train/waypointmanager/CMakeFiles /home/nikto_b/Documents/C++/fantastic-train/waypointmanager/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikto_b/Documents/C++/fantastic-train/waypointmanager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named waypointlib

# Build rule for target.
waypointlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 waypointlib
.PHONY : waypointlib

# fast build rule for target.
waypointlib/fast:
	$(MAKE) -f CMakeFiles/waypointlib.dir/build.make CMakeFiles/waypointlib.dir/build
.PHONY : waypointlib/fast

#=============================================================================
# Target rules for targets named waypointmanager

# Build rule for target.
waypointmanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 waypointmanager
.PHONY : waypointmanager

# fast build rule for target.
waypointmanager/fast:
	$(MAKE) -f CMakeFiles/waypointmanager.dir/build.make CMakeFiles/waypointmanager.dir/build
.PHONY : waypointmanager/fast

Src/main.o: Src/main.cpp.o

.PHONY : Src/main.o

# target to build an object file
Src/main.cpp.o:
	$(MAKE) -f CMakeFiles/waypointlib.dir/build.make CMakeFiles/waypointlib.dir/Src/main.cpp.o
	$(MAKE) -f CMakeFiles/waypointmanager.dir/build.make CMakeFiles/waypointmanager.dir/Src/main.cpp.o
.PHONY : Src/main.cpp.o

Src/main.i: Src/main.cpp.i

.PHONY : Src/main.i

# target to preprocess a source file
Src/main.cpp.i:
	$(MAKE) -f CMakeFiles/waypointlib.dir/build.make CMakeFiles/waypointlib.dir/Src/main.cpp.i
	$(MAKE) -f CMakeFiles/waypointmanager.dir/build.make CMakeFiles/waypointmanager.dir/Src/main.cpp.i
.PHONY : Src/main.cpp.i

Src/main.s: Src/main.cpp.s

.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.cpp.s:
	$(MAKE) -f CMakeFiles/waypointlib.dir/build.make CMakeFiles/waypointlib.dir/Src/main.cpp.s
	$(MAKE) -f CMakeFiles/waypointmanager.dir/build.make CMakeFiles/waypointmanager.dir/Src/main.cpp.s
.PHONY : Src/main.cpp.s

Src/manager.o: Src/manager.cpp.o

.PHONY : Src/manager.o

# target to build an object file
Src/manager.cpp.o:
	$(MAKE) -f CMakeFiles/waypointlib.dir/build.make CMakeFiles/waypointlib.dir/Src/manager.cpp.o
	$(MAKE) -f CMakeFiles/waypointmanager.dir/build.make CMakeFiles/waypointmanager.dir/Src/manager.cpp.o
.PHONY : Src/manager.cpp.o

Src/manager.i: Src/manager.cpp.i

.PHONY : Src/manager.i

# target to preprocess a source file
Src/manager.cpp.i:
	$(MAKE) -f CMakeFiles/waypointlib.dir/build.make CMakeFiles/waypointlib.dir/Src/manager.cpp.i
	$(MAKE) -f CMakeFiles/waypointmanager.dir/build.make CMakeFiles/waypointmanager.dir/Src/manager.cpp.i
.PHONY : Src/manager.cpp.i

Src/manager.s: Src/manager.cpp.s

.PHONY : Src/manager.s

# target to generate assembly for a file
Src/manager.cpp.s:
	$(MAKE) -f CMakeFiles/waypointlib.dir/build.make CMakeFiles/waypointlib.dir/Src/manager.cpp.s
	$(MAKE) -f CMakeFiles/waypointmanager.dir/build.make CMakeFiles/waypointmanager.dir/Src/manager.cpp.s
.PHONY : Src/manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... waypointlib"
	@echo "... edit_cache"
	@echo "... waypointmanager"
	@echo "... Src/main.o"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
	@echo "... Src/manager.o"
	@echo "... Src/manager.i"
	@echo "... Src/manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

